#  飞书
APP_ID: cli_a37f4b70c3f7d013
APP_SECRET: qr2DAnYPaacbM1s1qCNwgdzffaui5Tuy
APP_ENCRYPT_KEY: E6aXp1pqFW1wslhAfFhGgeYzD6iLTUAD
APP_VERIFICATION_TOKEN: SCGiQeq94ZEXEqjlQGMMZeGY3DZdabVj
# 请确保和飞书应用管理平台中的设置一致 
BOT_NAME: ChatGPT
# openAI
OPENAI_KEY: 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
